pub mod login;
pub mod register;
pub mod home;
pub mod article;
pub mod editor_v2;
pub mod profile;
pub mod search;
pub mod tags;
pub mod settings;
pub mod series;
pub mod series_detail;
pub mod publications;
pub mod publication_detail;
pub mod domain_management;
pub mod subscription_plans;
pub mod my_subscriptions;
pub mod earnings;

pub use login::LoginPage;
pub use register::RegisterPage;
pub use home::HomePage;
pub use article::ArticlePage;
pub use editor_v2::EditorV2Page;
pub use profile::{ProfilePage, ProfileByIdPage};
pub use search::SearchPage;
pub use tags::{TagsPage, TagDetailPage};
pub use settings::SettingsPage;
pub use series::SeriesManagePage;
pub use series_detail::SeriesDetailPage;
pub use publications::PublicationsPage;
pub use publication_detail::PublicationDetailPage;
pub use domain_management::DomainManagementPage;
pub use subscription_plans::SubscriptionPlansPage;
pub use my_subscriptions::MySubscriptionsPage;
pub use earnings::EarningsPage;